FROM ruby:2.3
WORKDIR /code
ADD Gemfile /code/Gemfile
ADD Gemfile.lock /code/Gemfile.lock
RUN bundle install --verbose
ADD . /code

ENV SLACK_TEAM_AWESOME_TOKEN=$SLACK_TEAM_AWESOME_TOKEN
ENV SLACK_BOT_AUTONOMY_TOKEN=$SLACK_BOT_AUTONOMY_TOKEN
ENV TWITTER_CONSUMER_KEY=$TWITTER_CONSUMER_KEY
ENV TWITTER_CONSUMER_SECRET=$TWITTER_CONSUMER_SECRET
ENV TWITTER_ACCESS_TOKEN=$TWITTER_ACCESS_TOKEN
ENV TWITTER_ACCESS_SECRET=$TWITTER_ACCESS_SECRET
